#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.1.4f1_ffa3a7a2dd7d"
#define UNITY_VERSION_FULL_NICE "2019.1.4f1 (ffa3a7a2dd7d)"
#define UNITY_VERSION_BLD 16753575
#define UNITY_VERSION_DATE 1558105384
#define UNITY_VERSION_WIN "2019.1.4.16753575"
#define UNITY_VERSION_BRANCH "2019.1/staging"
